import './js/gallery-popular-films';
import { loader } from './js/loader';
import './js/teamModal.js';
// import { modal_film } from './js/modal-film';
import { fetch } from './js/fetch-movie';
import { pagination } from './js/pagination';
import { keyMovieQuery } from './js/keyMovieQuery';
import './js/backToTop';
import './js/btn-in-modal';
import { darkOn } from './js/darkOn';
